CREATE TABLE CLIENTE (
    ID      BIGINT       NOT NULL AUTO_INCREMENT,
    NOME    VARCHAR(100) NOT NULL,
    CPF     VARCHAR(14)  NOT NULL,
    SENHA   CHAR(4)      NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

INSERT INTO CLIENTE (NOME, CPF, SENHA) VALUES ('Laire F. Borges', '123.456.789-11', '1759');
INSERT INTO CLIENTE (NOME, CPF, SENHA) VALUES ('Antonio Carvalho Jr.', '111.333.777-99', '4463');

CREATE TABLE CONTA (
    ID         BIGINT        NOT NULL AUTO_INCREMENT,
    AGENCIA    VARCHAR(10)   NOT NULL,
    CODIGO     VARCHAR(10)   NOT NULL,
    TIPO       VARCHAR(10)   NOT NULL,
    CLIENTE_ID BIGINT        NOT NULL,
    SALDO      DECIMAL(9, 2) NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY (ID),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);

INSERT INTO CONTA (AGENCIA, CODIGO, TIPO, CLIENTE_ID, SALDO) VALUES ('1158-X', '65893-0', 'CC', 1, 100.00);
INSERT INTO CONTA (AGENCIA, CODIGO, TIPO, CLIENTE_ID, SALDO) VALUES ('1158-X', '51112-0', 'CP', 2, 50.00);
