CREATE TABLE CLIENTE (
    ID      BIGINT       NOT NULL AUTO_INCREMENT,
    CID      BIGINT      NULL,
    NOME    VARCHAR(100) NOT NULL,
    CPF     VARCHAR(14)  NULL,
    SENHA   CHAR(4)      NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID)
);

INSERT INTO CLIENTE (NOME, CPF, SENHA, CID) VALUES ('Laire F. Borges', '111', '1759', 11);
INSERT INTO CLIENTE (NOME, CPF, SENHA, CID) VALUES ('Antonio Carvalho Jr.', '222', '4463', 22);
INSERT INTO CLIENTE (NOME, CPF, SENHA, CID) VALUES ('CCCCCCCCCCC', null, '9999', 33);

CREATE TABLE CLIENTE_DOIS (
    ID      BIGINT       NOT NULL,
    NOME    VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CLIENTE_DOIS PRIMARY KEY (ID)
);

create sequence cliente_dois_sequ start with 77;

INSERT INTO CLIENTE_DOIS (ID, NOME) VALUES (1, 'AAA');
INSERT INTO CLIENTE_DOIS (ID, NOME) VALUES (2, 'bbb');
INSERT INTO CLIENTE_DOIS (ID, NOME) VALUES (3, 'ccc');

CREATE TABLE CONTA (
    ID         BIGINT        NOT NULL AUTO_INCREMENT,
    AGENCIA    VARCHAR(10)   NOT NULL,
    CODIGO     VARCHAR(10)   NOT NULL,
    TIPO       VARCHAR(10)   NOT NULL,
    CLIENTE_ID BIGINT        NOT NULL,
    SALDO      DECIMAL(9, 2) NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY (ID),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE (ID)
);

INSERT INTO CONTA (AGENCIA, CODIGO, TIPO, CLIENTE_ID, SALDO) VALUES ('1158-X', '65893-0', 'CC', 1, 100.00);
INSERT INTO CONTA (AGENCIA, CODIGO, TIPO, CLIENTE_ID, SALDO) VALUES ('1158-X', '51112-0', 'CP', 2, 50.00);
